### ISSUE TITLE
FamilyControls.FamilyControlsError Code=2

### ISSUE THREAD

**Issue by CavyX1ao** [agarrharr/Homework#3]
Hi Sir,
when I tried to build the project on my device, I get an error "Domain=FamilyControls.FamilyControlsError Code=2 '(null)'".
I have settle a family group which include a an organizer and a parent, the test device is with parent apple id logged in.
The signing & capability of Family Controls has been added.
Could I get some help with that, Thank you so much.

**Comment by CavyX1ao** [comment]
Sorry, figure it out by reading annotation carefully to set logged id as child. Thank you so much.

**Comment by agarrharr** [comment]
Did you get the app to work? I haven't been able to get it to work. What did you do? Did you have to change the code?

**Comment by CavyX1ao** [comment]
> Did you get the app to work? I haven't been able to get it to work. What did you do? Did you have to change the code?

I did not do any change on code. Just to use a physical phone to run and log a new child apple account on it. It would be added from settings, family sharing part. And the age of a child must be under 13.
